first pass at adding maemo fixed gtk2 pkgconfig detect added hildon pkgconfig detect fixed(?) pixbuf error on some gtk/cairo installs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -668,10 +668,15 @@ OBJEXT
 CPP
 GREP
 EGREP
-pkggtk2
+PKG_CONFIG
+pkggtk2_CFLAGS
+pkggtk2_LIBS
 gtkconf
+pkghildon_CFLAGS
+pkghildon_LIBS
 TARGETS
 GTKLIBS
+HILDLIBS
 CURSLIBS
 LIBOBJS
 LTLIBOBJS'
@@ -684,7 +689,12 @@ CFLAGS
 LDFLAGS
 LIBS
 CPPFLAGS
-CPP'
+CPP
+PKG_CONFIG
+pkggtk2_CFLAGS
+pkggtk2_LIBS
+pkghildon_CFLAGS
+pkghildon_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1263,6 +1273,15 @@ Some influential environment variables:
   CPPFLAGS    C/C++/Objective C preprocessor flags, e.g. -I<include dir> if
               you have headers in a nonstandard directory <include dir>
   CPP         C preprocessor
+  PKG_CONFIG  path to pkg-config utility
+  pkggtk2_CFLAGS
+              C compiler flags for pkggtk2, overriding pkg-config
+  pkggtk2_LIBS
+              linker flags for pkggtk2, overriding pkg-config
+  pkghildon_CFLAGS
+              C compiler flags for pkghildon, overriding pkg-config
+  pkghildon_LIBS
+              linker flags for pkghildon, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -4982,24 +5001,30 @@ fi
 
 
 
-# Extract the first word of "pkg-config gtk+-2.0", so it can be a program name with args.
-set dummy pkg-config gtk+-2.0; ac_word=$2
+
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_prog_pkggtk2+set}" = set; then
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  if test -n "$pkggtk2"; then
-  ac_cv_prog_pkggtk2="$pkggtk2" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_pkggtk2="yes"
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -5007,19 +5032,166 @@ done
 done
 IFS=$as_save_IFS
 
-  test -z "$ac_cv_prog_pkggtk2" && ac_cv_prog_pkggtk2="no"
+  ;;
+esac
 fi
-fi
-pkggtk2=$ac_cv_prog_pkggtk2
-if test -n "$pkggtk2"; then
-  { echo "$as_me:$LINENO: result: $pkggtk2" >&5
-echo "${ECHO_T}$pkggtk2" >&6; }
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
 
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_ac_pt_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $ac_pt_PKG_CONFIG" >&5
+echo "${ECHO_T}$ac_pt_PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&5
+echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.9.0
+	{ echo "$as_me:$LINENO: checking pkg-config is at least version $_pkg_min_version" >&5
+echo $ECHO_N "checking pkg-config is at least version $_pkg_min_version... $ECHO_C" >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		PKG_CONFIG=""
+	fi
+
+fi
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for pkggtk2" >&5
+echo $ECHO_N "checking for pkggtk2... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$pkggtk2_CFLAGS"; then
+        pkg_cv_pkggtk2_CFLAGS="$pkggtk2_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_pkggtk2_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$pkggtk2_LIBS"; then
+        pkg_cv_pkggtk2_LIBS="$pkggtk2_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_pkggtk2_LIBS=`$PKG_CONFIG --libs "gtk+-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        pkggtk2_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "gtk+-2.0"`
+        else
+	        pkggtk2_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$pkggtk2_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                pkggtk2=no
+elif test $pkg_failed = untried; then
+	pkggtk2=no
+else
+	pkggtk2_CFLAGS=$pkg_cv_pkggtk2_CFLAGS
+	pkggtk2_LIBS=$pkg_cv_pkggtk2_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	pkggtk2=yes
+fi
 if test "$pkggtk2" = "yes" -a "$forcegtk" != "1"; then
 	GTK_CONFIG="pkg-config gtk+-2.0"
 	GTK2="yes"
@@ -5296,6 +5468,85 @@ echo "$as_me: WARNING: *** Gtk2 + Cairo is now required for the GTK ui" >&2;}
 		fi
 
   	fi
+
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for pkghildon" >&5
+echo $ECHO_N "checking for pkghildon... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$pkghildon_CFLAGS"; then
+        pkg_cv_pkghildon_CFLAGS="$pkghildon_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"hildon-1\"") >&5
+  ($PKG_CONFIG --exists --print-errors "hildon-1") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_pkghildon_CFLAGS=`$PKG_CONFIG --cflags "hildon-1" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$pkghildon_LIBS"; then
+        pkg_cv_pkghildon_LIBS="$pkghildon_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"hildon-1\"") >&5
+  ($PKG_CONFIG --exists --print-errors "hildon-1") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_pkghildon_LIBS=`$PKG_CONFIG --libs "hildon-1" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        pkghildon_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "hildon-1"`
+        else
+	        pkghildon_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "hildon-1"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$pkghildon_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                pkghildon=no
+elif test $pkg_failed = untried; then
+	pkghildon=no
+else
+	pkghildon_CFLAGS=$pkg_cv_pkghildon_CFLAGS
+	pkghildon_LIBS=$pkg_cv_pkghildon_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	pkghildon=yes
+fi
+	if test "$pkghildon" = "yes"; then
+		HILD_CONFIG="pkg-config hildon-1"
+		HILD="yes"
+	  	CFLAGS="$CFLAGS `$HILD_CONFIG --cflags`"
+	  	HILDLIBS="`$HILD_CONFIG --libs`"
+		TARGETS="$TARGETS spectool_hildon"
+	fi
 fi
 
 { echo "$as_me:$LINENO: checking for Linux headers with DEVFS_DISCONNECT support" >&5
@@ -5364,6 +5615,7 @@ else
 	{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
+
 
 
 
@@ -6045,16 +6297,21 @@ OBJEXT!$OBJEXT$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
-pkggtk2!$pkggtk2$ac_delim
+PKG_CONFIG!$PKG_CONFIG$ac_delim
+pkggtk2_CFLAGS!$pkggtk2_CFLAGS$ac_delim
+pkggtk2_LIBS!$pkggtk2_LIBS$ac_delim
 gtkconf!$gtkconf$ac_delim
+pkghildon_CFLAGS!$pkghildon_CFLAGS$ac_delim
+pkghildon_LIBS!$pkghildon_LIBS$ac_delim
 TARGETS!$TARGETS$ac_delim
 GTKLIBS!$GTKLIBS$ac_delim
+HILDLIBS!$HILDLIBS$ac_delim
 CURSLIBS!$CURSLIBS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 62; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 67; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
